import { MigrationInterface, QueryRunner } from "typeorm";

export class LatestSchema1740891202807 implements MigrationInterface {
    name = 'LatestSchema1740891202807'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "car_brand" ("id" character varying NOT NULL, "isActive" boolean NOT NULL DEFAULT true, "isDeleted" boolean NOT NULL DEFAULT false, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP, "code" character varying NOT NULL, "slug" character varying NOT NULL, "logo" character varying, "coverImage" character varying, CONSTRAINT "UQ_5c2068e6cce7390d9857cb72f4a" UNIQUE ("code"), CONSTRAINT "UQ_a0b95ca1e3f4bd6af82e221ac2b" UNIQUE ("slug"), CONSTRAINT "PK_cbaa76a620e6e21773085a96bf1" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "car_brand_translation" ("id" character varying NOT NULL, "isActive" boolean NOT NULL DEFAULT true, "isDeleted" boolean NOT NULL DEFAULT false, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP, "locale" character varying NOT NULL, "parentId" character varying NOT NULL, "name" character varying NOT NULL, "shortDescription" character varying, "description" character varying, "metaTitle" character varying, "metaDescription" character varying, "metaTags" character varying, CONSTRAINT "PK_2eb312137e6944b4c65633d02a5" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "car_model" ("id" character varying NOT NULL, "isActive" boolean NOT NULL DEFAULT true, "isDeleted" boolean NOT NULL DEFAULT false, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP, "code" character varying NOT NULL, "slug" character varying NOT NULL, "brandId" character varying, CONSTRAINT "UQ_385528f59b6b66e3d55195fde6b" UNIQUE ("code"), CONSTRAINT "UQ_69ecf6e8d8a4ef384ac04da7c82" UNIQUE ("slug"), CONSTRAINT "PK_525071eea12c671d67e35a5cbc8" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "car_model_translation" ("id" character varying NOT NULL, "isActive" boolean NOT NULL DEFAULT true, "isDeleted" boolean NOT NULL DEFAULT false, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP, "locale" character varying NOT NULL, "parentId" character varying NOT NULL, "name" character varying NOT NULL, "shortDescription" character varying, "description" character varying, "metaTitle" character varying, "metaDescription" character varying, "metaTags" character varying, CONSTRAINT "PK_a0b9bb481eae65c6d4aa3db5cb5" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "car_feature" ("id" character varying NOT NULL, "isActive" boolean NOT NULL DEFAULT true, "isDeleted" boolean NOT NULL DEFAULT false, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP, "code" character varying NOT NULL, "slug" character varying NOT NULL, CONSTRAINT "UQ_0f23798c980861bebd2b8600b42" UNIQUE ("code"), CONSTRAINT "UQ_db7015d91750d73441c0af55446" UNIQUE ("slug"), CONSTRAINT "PK_ddcb41416b2d98c630ebc93640b" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."car_feature_translation_category_enum" AS ENUM('SAFETY', 'COMFORT', 'TECHNOLOGY', 'PERFORMANCE', 'LUXURY', 'OTHER')`);
        await queryRunner.query(`CREATE TABLE "car_feature_translation" ("id" character varying NOT NULL, "isActive" boolean NOT NULL DEFAULT true, "isDeleted" boolean NOT NULL DEFAULT false, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP, "locale" character varying NOT NULL, "parentId" character varying NOT NULL, "name" character varying NOT NULL, "shortDescription" character varying, "description" character varying, "category" "public"."car_feature_translation_category_enum" NOT NULL, "isHighlighted" boolean NOT NULL DEFAULT false, CONSTRAINT "PK_fab704acd6f9930c8aa650f8b47" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "rental_pricing" ("id" character varying NOT NULL, "isActive" boolean NOT NULL DEFAULT true, "isDeleted" boolean NOT NULL DEFAULT false, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP, "duration" integer NOT NULL, "unit" character varying NOT NULL, "price" integer NOT NULL, "currency" character varying NOT NULL, "carId" character varying, CONSTRAINT "PK_e594cf4ef33b063dbc90f319a63" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."car_media_type_enum" AS ENUM('audio', 'video', 'image', 'model_3D')`);
        await queryRunner.query(`CREATE TABLE "car_media" ("id" character varying NOT NULL, "isActive" boolean NOT NULL DEFAULT true, "isDeleted" boolean NOT NULL DEFAULT false, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP, "url" character varying NOT NULL, "type" "public"."car_media_type_enum" NOT NULL, "isThumbnail" boolean NOT NULL DEFAULT false, "title" character varying, "description" text, "position" integer NOT NULL, "carId" character varying, CONSTRAINT "PK_a1ed9e825e997cc6dbbd9c55b60" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."car_document_type_enum" AS ENUM('REGISTRATION', 'INSURANCE', 'MAINTENANCE', 'OWNERSHIP', 'INSPECTION', 'ACCIDENT', 'OTHER')`);
        await queryRunner.query(`CREATE TABLE "car_document" ("id" character varying NOT NULL, "isActive" boolean NOT NULL DEFAULT true, "isDeleted" boolean NOT NULL DEFAULT false, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP, "type" "public"."car_document_type_enum" NOT NULL, "title" character varying NOT NULL, "fileUrl" character varying NOT NULL, "issueDate" TIMESTAMP NOT NULL, "expiryDate" TIMESTAMP, "isVerified" boolean NOT NULL DEFAULT false, "verificationDate" TIMESTAMP, "carId" character varying, CONSTRAINT "PK_17bc47fd86a9b1defb8b9149f50" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "ownership_details" ("id" character varying NOT NULL, "isActive" boolean NOT NULL DEFAULT true, "isDeleted" boolean NOT NULL DEFAULT false, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP, "ownerType" character varying NOT NULL, "percentage" numeric(5,2) NOT NULL, "nftId" character varying, "acquiredDate" TIMESTAMP NOT NULL, "transferDate" TIMESTAMP, "status" character varying NOT NULL, "carId" character varying, "ownerId" character varying, CONSTRAINT "PK_e6b7828a8dd5598e6a94adec347" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."car_history_records_type_enum" AS ENUM('MAINTENANCE', 'RENTAL', 'SALE', 'OWNERSHIP_CHANGE', 'ACCIDENT', 'INSPECTION', 'LOCATION_CHANGE', 'MODIFICATION', 'DETAILS_UPDATED')`);
        await queryRunner.query(`CREATE TABLE "car_history_records" ("id" character varying NOT NULL, "isActive" boolean NOT NULL DEFAULT true, "isDeleted" boolean NOT NULL DEFAULT false, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP, "type" "public"."car_history_records_type_enum" NOT NULL, "date" TIMESTAMP NOT NULL, "description" text NOT NULL, "mileageAtTime" integer, "cost" jsonb, "performedBy" character varying, "nextScheduledDate" TIMESTAMP, "carId" character varying, CONSTRAINT "PK_33d621351a46a16e27da9bd25c9" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."car_category_enum" AS ENUM('LUXURY_SEDAN', 'SPORTS_CAR', 'SUV', 'CONVERTIBLE', 'EXOTIC', 'ELECTRIC_LUXURY', 'VINTAGE')`);
        await queryRunner.query(`CREATE TYPE "public"."car_fueltype_enum" AS ENUM('GASOLINE', 'DIESEL', 'ELECTRIC', 'HYBRID', 'HYDROGEN', 'PLUG_IN_HYBRID')`);
        await queryRunner.query(`CREATE TYPE "public"."car_transmission_enum" AS ENUM('AUTOMATIC', 'MANUAL', 'SEMI_AUTOMATIC', 'DUAL_CLUTCH', 'CVT')`);
        await queryRunner.query(`CREATE TYPE "public"."car_currentstatus_enum" AS ENUM('AVAILABLE', 'RENTED', 'RESERVED', 'IN_MAINTENANCE', 'IN_TRANSIT', 'SOLD', 'NOT_AVAILABLE')`);
        await queryRunner.query(`CREATE TYPE "public"."car_condition_enum" AS ENUM('EXCELLENT', 'VERY_GOOD', 'GOOD', 'FAIR', 'NEEDS_MAINTENANCE')`);
        await queryRunner.query(`CREATE TYPE "public"."car_inspectionstatus_enum" AS ENUM('PASSED', 'PENDING', 'FAILED', 'EXEMPTED')`);
        await queryRunner.query(`CREATE TABLE "car" ("id" character varying NOT NULL, "isActive" boolean NOT NULL DEFAULT true, "isDeleted" boolean NOT NULL DEFAULT false, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP, "slug" character varying NOT NULL, "vin" character varying NOT NULL, "blockchainId" character varying, "year" integer NOT NULL, "category" "public"."car_category_enum" NOT NULL, "fuelType" "public"."car_fueltype_enum" NOT NULL, "transmission" "public"."car_transmission_enum" NOT NULL, "doors" integer NOT NULL, "seats" integer NOT NULL, "engineSpecs" jsonb NOT NULL, "dimensions" jsonb NOT NULL, "virtualTourUrl" character varying, "metaverseAssetId" character varying, "currentStatus" "public"."car_currentstatus_enum" NOT NULL DEFAULT 'AVAILABLE', "listingType" text NOT NULL DEFAULT '["FOR_RENT"]', "acquisitionDate" TIMESTAMP, "mileage" integer NOT NULL, "condition" "public"."car_condition_enum" NOT NULL DEFAULT 'EXCELLENT', "inspectionStatus" "public"."car_inspectionstatus_enum" NOT NULL DEFAULT 'PENDING', "lastInspectionDate" TIMESTAMP, "nextInspectionDueDate" TIMESTAMP, "brandId" character varying, "modelId" character varying, CONSTRAINT "UQ_d37d214d98d6f5cce4479d57843" UNIQUE ("slug"), CONSTRAINT "UQ_e917bf949f80860e817b74006e8" UNIQUE ("vin"), CONSTRAINT "PK_55bbdeb14e0b1d7ab417d11ee6d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "car_translation" ("id" character varying NOT NULL, "isActive" boolean NOT NULL DEFAULT true, "isDeleted" boolean NOT NULL DEFAULT false, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP, "locale" character varying NOT NULL, "parentId" character varying NOT NULL, "color" jsonb NOT NULL, "interiorColor" jsonb NOT NULL, "name" character varying NOT NULL, "shortDescription" character varying, "description" character varying, "metaTitle" character varying, "metaDescription" character varying, "metaTags" character varying, CONSTRAINT "PK_0173274695f9a32f178fac55e88" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "car_history_records_documents_car_document" ("carHistoryRecordsId" character varying NOT NULL, "carDocumentId" character varying NOT NULL, CONSTRAINT "PK_0d2117bf27fe1b44b44b23c9e21" PRIMARY KEY ("carHistoryRecordsId", "carDocumentId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_c1a6bcf48137d96551ae241801" ON "car_history_records_documents_car_document" ("carHistoryRecordsId") `);
        await queryRunner.query(`CREATE INDEX "IDX_e90fc83ecd3744e1fcbce72ab2" ON "car_history_records_documents_car_document" ("carDocumentId") `);
        await queryRunner.query(`CREATE TABLE "car_features_car_feature" ("carId" character varying NOT NULL, "carFeatureId" character varying NOT NULL, CONSTRAINT "PK_c60ee63a79fea97ddd25ac49a67" PRIMARY KEY ("carId", "carFeatureId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_6ad79e122d4c26b0cb6c6302f4" ON "car_features_car_feature" ("carId") `);
        await queryRunner.query(`CREATE INDEX "IDX_78cc27204101d69a79ab649980" ON "car_features_car_feature" ("carFeatureId") `);
        await queryRunner.query(`ALTER TABLE "product" ADD "isActive" boolean NOT NULL DEFAULT true`);
        await queryRunner.query(`ALTER TABLE "product" ADD "isDeleted" boolean NOT NULL DEFAULT false`);
        await queryRunner.query(`ALTER TABLE "product" ADD "deletedAt" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "product_brand" ADD "isActive" boolean NOT NULL DEFAULT true`);
        await queryRunner.query(`ALTER TABLE "product_brand" ADD "isDeleted" boolean NOT NULL DEFAULT false`);
        await queryRunner.query(`ALTER TABLE "product_brand" ADD "deletedAt" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "product_category" ADD "isActive" boolean NOT NULL DEFAULT true`);
        await queryRunner.query(`ALTER TABLE "product_category" ADD "isDeleted" boolean NOT NULL DEFAULT false`);
        await queryRunner.query(`ALTER TABLE "product_category" ADD "deletedAt" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "product_tag" ADD "isActive" boolean NOT NULL DEFAULT true`);
        await queryRunner.query(`ALTER TABLE "product_tag" ADD "isDeleted" boolean NOT NULL DEFAULT false`);
        await queryRunner.query(`ALTER TABLE "product_tag" ADD "deletedAt" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "product_variant" ADD "isActive" boolean NOT NULL DEFAULT true`);
        await queryRunner.query(`ALTER TABLE "product_variant" ADD "isDeleted" boolean NOT NULL DEFAULT false`);
        await queryRunner.query(`ALTER TABLE "product_variant" ADD "deletedAt" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "product_attribute_group" ADD "isActive" boolean NOT NULL DEFAULT true`);
        await queryRunner.query(`ALTER TABLE "product_attribute_group" ADD "isDeleted" boolean NOT NULL DEFAULT false`);
        await queryRunner.query(`ALTER TABLE "product_attribute_group" ADD "deletedAt" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "product_attribute_option" ADD "isActive" boolean NOT NULL DEFAULT true`);
        await queryRunner.query(`ALTER TABLE "product_attribute_option" ADD "isDeleted" boolean NOT NULL DEFAULT false`);
        await queryRunner.query(`ALTER TABLE "product_attribute_option" ADD "deletedAt" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "product_media" ADD "isActive" boolean NOT NULL DEFAULT true`);
        await queryRunner.query(`ALTER TABLE "product_media" ADD "isDeleted" boolean NOT NULL DEFAULT false`);
        await queryRunner.query(`ALTER TABLE "product_media" ADD "deletedAt" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "supplier" ADD "isActive" boolean NOT NULL DEFAULT true`);
        await queryRunner.query(`ALTER TABLE "supplier" ADD "isDeleted" boolean NOT NULL DEFAULT false`);
        await queryRunner.query(`ALTER TABLE "supplier" ADD "deletedAt" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "session" ADD "isDeleted" boolean NOT NULL DEFAULT false`);
        await queryRunner.query(`ALTER TABLE "session" ADD "deletedAt" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "otp" ADD "isActive" boolean NOT NULL DEFAULT true`);
        await queryRunner.query(`ALTER TABLE "otp" ADD "isDeleted" boolean NOT NULL DEFAULT false`);
        await queryRunner.query(`ALTER TABLE "otp" ADD "deletedAt" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "role" ADD "isActive" boolean NOT NULL DEFAULT true`);
        await queryRunner.query(`ALTER TABLE "role" ADD "isDeleted" boolean NOT NULL DEFAULT false`);
        await queryRunner.query(`ALTER TABLE "role" ADD "deletedAt" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "permission" ADD "isActive" boolean NOT NULL DEFAULT true`);
        await queryRunner.query(`ALTER TABLE "permission" ADD "isDeleted" boolean NOT NULL DEFAULT false`);
        await queryRunner.query(`ALTER TABLE "permission" ADD "deletedAt" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "resource" ADD "isActive" boolean NOT NULL DEFAULT true`);
        await queryRunner.query(`ALTER TABLE "resource" ADD "isDeleted" boolean NOT NULL DEFAULT false`);
        await queryRunner.query(`ALTER TABLE "resource" ADD "deletedAt" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "user" ADD "deletedAt" TIMESTAMP`);
        await queryRunner.query(`ALTER TYPE "public"."product_media_type_enum" RENAME TO "product_media_type_enum_old"`);
        await queryRunner.query(`CREATE TYPE "public"."product_media_type_enum" AS ENUM('video', 'audio', 'image', 'pdf', 'document', 'model_3D', 'other')`);
        await queryRunner.query(`ALTER TABLE "product_media" ALTER COLUMN "type" TYPE "public"."product_media_type_enum" USING "type"::"text"::"public"."product_media_type_enum"`);
        await queryRunner.query(`DROP TYPE "public"."product_media_type_enum_old"`);
        await queryRunner.query(`ALTER TABLE "session" ALTER COLUMN "isActive" SET DEFAULT true`);
        await queryRunner.query(`ALTER TABLE "car_brand_translation" ADD CONSTRAINT "FK_ad3a964d0467bfbd60f07aff208" FOREIGN KEY ("parentId") REFERENCES "car_brand"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "car_model" ADD CONSTRAINT "FK_e3920bc43fe2f7de05911630b3e" FOREIGN KEY ("brandId") REFERENCES "car_brand"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "car_model_translation" ADD CONSTRAINT "FK_e4d5d3aacbf456674b2f324eafc" FOREIGN KEY ("parentId") REFERENCES "car_model"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "car_feature_translation" ADD CONSTRAINT "FK_111140d158235ab46b2e46c58dc" FOREIGN KEY ("parentId") REFERENCES "car_feature"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "rental_pricing" ADD CONSTRAINT "FK_4835fdf08064596b83635dd3ddd" FOREIGN KEY ("carId") REFERENCES "car"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "car_media" ADD CONSTRAINT "FK_17d99d40d82a78b2242f9537e82" FOREIGN KEY ("carId") REFERENCES "car"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "car_document" ADD CONSTRAINT "FK_d5cca4744fd1d313697828d1aed" FOREIGN KEY ("carId") REFERENCES "car"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "ownership_details" ADD CONSTRAINT "FK_cbfe48923efcbf189b1a590af86" FOREIGN KEY ("carId") REFERENCES "car"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "ownership_details" ADD CONSTRAINT "FK_643ba03b1af94090362839e65dc" FOREIGN KEY ("ownerId") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "car_history_records" ADD CONSTRAINT "FK_84d44f5455c910bb9f53a1ffb38" FOREIGN KEY ("carId") REFERENCES "car"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "car" ADD CONSTRAINT "FK_728700aee449838965f5cf87cee" FOREIGN KEY ("brandId") REFERENCES "car_brand"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "car" ADD CONSTRAINT "FK_c40870af5230c4d117729c8299f" FOREIGN KEY ("modelId") REFERENCES "car_model"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "car_translation" ADD CONSTRAINT "FK_8744f80ba2253300b7252be6351" FOREIGN KEY ("parentId") REFERENCES "car"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "car_history_records_documents_car_document" ADD CONSTRAINT "FK_c1a6bcf48137d96551ae241801b" FOREIGN KEY ("carHistoryRecordsId") REFERENCES "car_history_records"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "car_history_records_documents_car_document" ADD CONSTRAINT "FK_e90fc83ecd3744e1fcbce72ab27" FOREIGN KEY ("carDocumentId") REFERENCES "car_document"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "car_features_car_feature" ADD CONSTRAINT "FK_6ad79e122d4c26b0cb6c6302f44" FOREIGN KEY ("carId") REFERENCES "car"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "car_features_car_feature" ADD CONSTRAINT "FK_78cc27204101d69a79ab649980c" FOREIGN KEY ("carFeatureId") REFERENCES "car_feature"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "car_features_car_feature" DROP CONSTRAINT "FK_78cc27204101d69a79ab649980c"`);
        await queryRunner.query(`ALTER TABLE "car_features_car_feature" DROP CONSTRAINT "FK_6ad79e122d4c26b0cb6c6302f44"`);
        await queryRunner.query(`ALTER TABLE "car_history_records_documents_car_document" DROP CONSTRAINT "FK_e90fc83ecd3744e1fcbce72ab27"`);
        await queryRunner.query(`ALTER TABLE "car_history_records_documents_car_document" DROP CONSTRAINT "FK_c1a6bcf48137d96551ae241801b"`);
        await queryRunner.query(`ALTER TABLE "car_translation" DROP CONSTRAINT "FK_8744f80ba2253300b7252be6351"`);
        await queryRunner.query(`ALTER TABLE "car" DROP CONSTRAINT "FK_c40870af5230c4d117729c8299f"`);
        await queryRunner.query(`ALTER TABLE "car" DROP CONSTRAINT "FK_728700aee449838965f5cf87cee"`);
        await queryRunner.query(`ALTER TABLE "car_history_records" DROP CONSTRAINT "FK_84d44f5455c910bb9f53a1ffb38"`);
        await queryRunner.query(`ALTER TABLE "ownership_details" DROP CONSTRAINT "FK_643ba03b1af94090362839e65dc"`);
        await queryRunner.query(`ALTER TABLE "ownership_details" DROP CONSTRAINT "FK_cbfe48923efcbf189b1a590af86"`);
        await queryRunner.query(`ALTER TABLE "car_document" DROP CONSTRAINT "FK_d5cca4744fd1d313697828d1aed"`);
        await queryRunner.query(`ALTER TABLE "car_media" DROP CONSTRAINT "FK_17d99d40d82a78b2242f9537e82"`);
        await queryRunner.query(`ALTER TABLE "rental_pricing" DROP CONSTRAINT "FK_4835fdf08064596b83635dd3ddd"`);
        await queryRunner.query(`ALTER TABLE "car_feature_translation" DROP CONSTRAINT "FK_111140d158235ab46b2e46c58dc"`);
        await queryRunner.query(`ALTER TABLE "car_model_translation" DROP CONSTRAINT "FK_e4d5d3aacbf456674b2f324eafc"`);
        await queryRunner.query(`ALTER TABLE "car_model" DROP CONSTRAINT "FK_e3920bc43fe2f7de05911630b3e"`);
        await queryRunner.query(`ALTER TABLE "car_brand_translation" DROP CONSTRAINT "FK_ad3a964d0467bfbd60f07aff208"`);
        await queryRunner.query(`ALTER TABLE "session" ALTER COLUMN "isActive" DROP DEFAULT`);
        await queryRunner.query(`CREATE TYPE "public"."product_media_type_enum_old" AS ENUM('video', 'audio', 'image', 'pdf', 'document', 'other')`);
        await queryRunner.query(`ALTER TABLE "product_media" ALTER COLUMN "type" TYPE "public"."product_media_type_enum_old" USING "type"::"text"::"public"."product_media_type_enum_old"`);
        await queryRunner.query(`DROP TYPE "public"."product_media_type_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."product_media_type_enum_old" RENAME TO "product_media_type_enum"`);
        await queryRunner.query(`ALTER TABLE "user" DROP COLUMN "deletedAt"`);
        await queryRunner.query(`ALTER TABLE "resource" DROP COLUMN "deletedAt"`);
        await queryRunner.query(`ALTER TABLE "resource" DROP COLUMN "isDeleted"`);
        await queryRunner.query(`ALTER TABLE "resource" DROP COLUMN "isActive"`);
        await queryRunner.query(`ALTER TABLE "permission" DROP COLUMN "deletedAt"`);
        await queryRunner.query(`ALTER TABLE "permission" DROP COLUMN "isDeleted"`);
        await queryRunner.query(`ALTER TABLE "permission" DROP COLUMN "isActive"`);
        await queryRunner.query(`ALTER TABLE "role" DROP COLUMN "deletedAt"`);
        await queryRunner.query(`ALTER TABLE "role" DROP COLUMN "isDeleted"`);
        await queryRunner.query(`ALTER TABLE "role" DROP COLUMN "isActive"`);
        await queryRunner.query(`ALTER TABLE "otp" DROP COLUMN "deletedAt"`);
        await queryRunner.query(`ALTER TABLE "otp" DROP COLUMN "isDeleted"`);
        await queryRunner.query(`ALTER TABLE "otp" DROP COLUMN "isActive"`);
        await queryRunner.query(`ALTER TABLE "session" DROP COLUMN "deletedAt"`);
        await queryRunner.query(`ALTER TABLE "session" DROP COLUMN "isDeleted"`);
        await queryRunner.query(`ALTER TABLE "supplier" DROP COLUMN "deletedAt"`);
        await queryRunner.query(`ALTER TABLE "supplier" DROP COLUMN "isDeleted"`);
        await queryRunner.query(`ALTER TABLE "supplier" DROP COLUMN "isActive"`);
        await queryRunner.query(`ALTER TABLE "product_media" DROP COLUMN "deletedAt"`);
        await queryRunner.query(`ALTER TABLE "product_media" DROP COLUMN "isDeleted"`);
        await queryRunner.query(`ALTER TABLE "product_media" DROP COLUMN "isActive"`);
        await queryRunner.query(`ALTER TABLE "product_attribute_option" DROP COLUMN "deletedAt"`);
        await queryRunner.query(`ALTER TABLE "product_attribute_option" DROP COLUMN "isDeleted"`);
        await queryRunner.query(`ALTER TABLE "product_attribute_option" DROP COLUMN "isActive"`);
        await queryRunner.query(`ALTER TABLE "product_attribute_group" DROP COLUMN "deletedAt"`);
        await queryRunner.query(`ALTER TABLE "product_attribute_group" DROP COLUMN "isDeleted"`);
        await queryRunner.query(`ALTER TABLE "product_attribute_group" DROP COLUMN "isActive"`);
        await queryRunner.query(`ALTER TABLE "product_variant" DROP COLUMN "deletedAt"`);
        await queryRunner.query(`ALTER TABLE "product_variant" DROP COLUMN "isDeleted"`);
        await queryRunner.query(`ALTER TABLE "product_variant" DROP COLUMN "isActive"`);
        await queryRunner.query(`ALTER TABLE "product_tag" DROP COLUMN "deletedAt"`);
        await queryRunner.query(`ALTER TABLE "product_tag" DROP COLUMN "isDeleted"`);
        await queryRunner.query(`ALTER TABLE "product_tag" DROP COLUMN "isActive"`);
        await queryRunner.query(`ALTER TABLE "product_category" DROP COLUMN "deletedAt"`);
        await queryRunner.query(`ALTER TABLE "product_category" DROP COLUMN "isDeleted"`);
        await queryRunner.query(`ALTER TABLE "product_category" DROP COLUMN "isActive"`);
        await queryRunner.query(`ALTER TABLE "product_brand" DROP COLUMN "deletedAt"`);
        await queryRunner.query(`ALTER TABLE "product_brand" DROP COLUMN "isDeleted"`);
        await queryRunner.query(`ALTER TABLE "product_brand" DROP COLUMN "isActive"`);
        await queryRunner.query(`ALTER TABLE "product" DROP COLUMN "deletedAt"`);
        await queryRunner.query(`ALTER TABLE "product" DROP COLUMN "isDeleted"`);
        await queryRunner.query(`ALTER TABLE "product" DROP COLUMN "isActive"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_78cc27204101d69a79ab649980"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_6ad79e122d4c26b0cb6c6302f4"`);
        await queryRunner.query(`DROP TABLE "car_features_car_feature"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e90fc83ecd3744e1fcbce72ab2"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c1a6bcf48137d96551ae241801"`);
        await queryRunner.query(`DROP TABLE "car_history_records_documents_car_document"`);
        await queryRunner.query(`DROP TABLE "car_translation"`);
        await queryRunner.query(`DROP TABLE "car"`);
        await queryRunner.query(`DROP TYPE "public"."car_inspectionstatus_enum"`);
        await queryRunner.query(`DROP TYPE "public"."car_condition_enum"`);
        await queryRunner.query(`DROP TYPE "public"."car_currentstatus_enum"`);
        await queryRunner.query(`DROP TYPE "public"."car_transmission_enum"`);
        await queryRunner.query(`DROP TYPE "public"."car_fueltype_enum"`);
        await queryRunner.query(`DROP TYPE "public"."car_category_enum"`);
        await queryRunner.query(`DROP TABLE "car_history_records"`);
        await queryRunner.query(`DROP TYPE "public"."car_history_records_type_enum"`);
        await queryRunner.query(`DROP TABLE "ownership_details"`);
        await queryRunner.query(`DROP TABLE "car_document"`);
        await queryRunner.query(`DROP TYPE "public"."car_document_type_enum"`);
        await queryRunner.query(`DROP TABLE "car_media"`);
        await queryRunner.query(`DROP TYPE "public"."car_media_type_enum"`);
        await queryRunner.query(`DROP TABLE "rental_pricing"`);
        await queryRunner.query(`DROP TABLE "car_feature_translation"`);
        await queryRunner.query(`DROP TYPE "public"."car_feature_translation_category_enum"`);
        await queryRunner.query(`DROP TABLE "car_feature"`);
        await queryRunner.query(`DROP TABLE "car_model_translation"`);
        await queryRunner.query(`DROP TABLE "car_model"`);
        await queryRunner.query(`DROP TABLE "car_brand_translation"`);
        await queryRunner.query(`DROP TABLE "car_brand"`);
    }

}
